// Do not edit this directly; if there are changes needed, edit the codegen and regenerate
int (*offersConfigure)(size_t hostPluginID);
void (*configure)(size_t hostPluginID, void* handle, void* qParentWidget);
void (*registerPluginID)(size_t hostPluginID, const char* id);
int (*processCommand)(size_t hostPluginID, uint64_t serverConnectionHandlerID, const char* command);
void (*currentServerConnectionChanged)(size_t hostPluginID, uint64_t serverConnectionHandlerID);
int (*requestAutoload)(size_t hostPluginID);
void (*onConnectStatusChangeEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, unsigned int errorNumber);
void (*onNewChannelEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, uint64_t channelParentID);
void (*onNewChannelCreatedEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, const char* invokerUniqueIdentifier);
void (*onDelChannelEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, const char* invokerUniqueIdentifier);
void (*onChannelMoveEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, const char* invokerUniqueIdentifier);
void (*onUpdateChannelEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, uint64_t channelID);
void (*onUpdateChannelEditedEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, const char* invokerUniqueIdentifier);
void (*onUpdateClientEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, const char* invokerUniqueIdentifier);
void (*onClientMoveEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, const char* moveMessage);
void (*onClientMoveSubscriptionEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, int visibility);
void (*onClientMoveTimeoutEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, const char* timeoutMessage);
void (*onClientMoveMovedEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, const char* moveMessage);
void (*onClientKickFromChannelEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, const char* kickMessage);
void (*onClientKickFromServerEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, const char* kickMessage);
void (*onClientIDsEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, const char* clientName);
void (*onClientIDsFinishedEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID);
void (*onServerEditedEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, const char* editerUniqueIdentifier);
void (*onServerUpdatedEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID);
int  (*onServerErrorEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, const char* extraMessage);
void (*onServerStopEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, const char* shutdownMessage);
int  (*onTextMessageEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, int ffIgnored);
void (*onTalkStatusChangeEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, uint16_t clientID);
void (*onConnectionInfoEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, uint16_t clientID);
void (*onServerConnectionInfoEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID);
void (*onChannelSubscribeEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, uint64_t channelID);
void (*onChannelSubscribeFinishedEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID);
void (*onChannelUnsubscribeEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, uint64_t channelID);
void (*onChannelUnsubscribeFinishedEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID);
void (*onChannelDescriptionUpdateEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, uint64_t channelID);
void (*onChannelPasswordChangedEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, uint64_t channelID);
void (*onPlaybackShutdownCompleteEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID);
void (*onSoundDeviceListChangedEvent)(size_t hostPluginID, const char* modeID, int playOrCap);
void (*onEditPlaybackVoiceDataEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, int channels);
void (*onEditPostProcessVoiceDataEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, unsigned int* channelFillMask);
void (*onEditMixedPlaybackVoiceDataEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, unsigned int* channelFillMask);
void (*onEditCapturedVoiceDataEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, int* edited);
void (*onCustom3dRolloffCalculationClientEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, float* volume);
void (*onCustom3dRolloffCalculationWaveEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, float* volume);
void (*onUserLoggingMessageEvent)(size_t hostPluginID, const char* logMessage, const char* completeLogString);
void (*onClientBanFromServerEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, const char* kickMessage);
int  (*onClientPokeEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, int ffIgnored);
void (*onClientSelfVariableUpdateEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, const char* newValue);
void (*onFileListEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, const char* returnCode);
void (*onFileListFinishedEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, const char* path);
void (*onFileInfoEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, uint64_t datetime);
void (*onServerGroupListEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, int saveDB);
void (*onServerGroupListFinishedEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID);
void (*onServerGroupByClientIDEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, uint64_t clientDatabaseID);
void (*onServerGroupPermListEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, int permissionSkip);
void (*onServerGroupPermListFinishedEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, uint64_t serverGroupID);
void (*onServerGroupClientListEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, const char* clientUniqueID);
void (*onChannelGroupListEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, int saveDB);
void (*onChannelGroupListFinishedEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID);
void (*onChannelGroupPermListEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, int permissionSkip);
void (*onChannelGroupPermListFinishedEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, uint64_t channelGroupID);
void (*onChannelPermListEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, int permissionSkip);
void (*onChannelPermListFinishedEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, uint64_t channelID);
void (*onClientPermListEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, int permissionSkip);
void (*onClientPermListFinishedEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, uint64_t clientDatabaseID);
void (*onChannelClientPermListEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, int permissionSkip);
void (*onChannelClientPermListFinishedEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, uint64_t clientDatabaseID);
void (*onClientChannelGroupChangedEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, const char* invokerUniqueIdentity);
int  (*onServerPermissionErrorEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, unsigned int failedPermissionID);
void (*onPermissionListGroupEndIDEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, unsigned int groupEndID);
void (*onPermissionListEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, const char* permissionDescription);
void (*onPermissionListFinishedEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID);
void (*onPermissionOverviewEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, int permissionSkip);
void (*onPermissionOverviewFinishedEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID);
void (*onServerGroupClientAddedEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, const char* invokerUniqueIdentity);
void (*onServerGroupClientDeletedEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, const char* invokerUniqueIdentity);
void (*onClientNeededPermissionsEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, int permissionValue);
void (*onClientNeededPermissionsFinishedEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID);
void (*onFileTransferStatusEvent)(size_t hostPluginID, uint16_t transferID, uint64_t serverConnectionHandlerID);
void (*onClientChatClosedEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, const char* clientUniqueIdentity);
void (*onClientChatComposingEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, const char* clientUniqueIdentity);
void (*onServerLogEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, const char* logMsg);
void (*onServerLogFinishedEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, uint64_t fileSize);
void (*onMessageListEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, int flagRead);
void (*onMessageGetEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, uint64_t timestamp);
void (*onClientDBIDfromUIDEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, uint64_t clientDatabaseID);
void (*onClientNamefromUIDEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, const char* clientNickName);
void (*onClientNamefromDBIDEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, const char* clientNickName);
void (*onComplainListEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, uint64_t timestamp);
void (*onBanListEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, const char* lastNickName);
void (*onClientServerQueryLoginPasswordEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, const char* loginPassword);
void (*onPluginCommandEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, const char* pluginCommand);
void (*onIncomingClientQueryEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, const char* commandText);
void (*onServerTemporaryPasswordListEvent)(size_t hostPluginID, uint64_t serverConnectionHandlerID, const char* targetChannelPW);
void (*onAvatarUpdated)(size_t hostPluginID, uint64_t serverConnectionHandlerID, const char* avatarPath);
void (*onHotkeyEvent)(size_t hostPluginID, const char* keyword);
void (*onHotkeyRecordedEvent)(size_t hostPluginID, const char* keyword, const char* key);
void (*onClientDisplayNameChanged)(size_t hostPluginID, uint64_t serverConnectionHandlerID, const char* uniqueClientIdentifier);
